INSERT INTO MOVIE(MOVIE_ID, MOVIE_NM) VALUES (1, 'WONDER WOMAN 1984');


INSERT INTO THEATRE(THEATRE_ID, SCREEN_NAME, THEATRE_NAME, MOVIE_ID, LOCATION) VALUES (1, 'SCREEN-1', 'GEETHA MULTIPLEX', 1, 'HYD');


INSERT INTO THEATRE_SCREEN_1(THTR_BKNG_SCRN_ID, BOOKING_VRSN, DATE_OF_BOOKING, SEAT_NUM, THEATRE_ID) VALUES (1, 0, '2021-05-11', 'A1', 1);
INSERT INTO THEATRE_SCREEN_1(THTR_BKNG_SCRN_ID, BOOKING_VRSN, DATE_OF_BOOKING, SEAT_NUM, THEATRE_ID) VALUES (2, 0, '2021-05-11', 'A2', 1);
INSERT INTO THEATRE_SCREEN_1(THTR_BKNG_SCRN_ID, BOOKING_VRSN, DATE_OF_BOOKING, SEAT_NUM, THEATRE_ID) VALUES (3, 0, '2021-05-11', 'A3', 1);
INSERT INTO THEATRE_SCREEN_1(THTR_BKNG_SCRN_ID, BOOKING_VRSN, DATE_OF_BOOKING, SEAT_NUM, THEATRE_ID) VALUES (4, 0, '2021-05-11', 'B1', 1);
INSERT INTO THEATRE_SCREEN_1(THTR_BKNG_SCRN_ID, BOOKING_VRSN, DATE_OF_BOOKING, SEAT_NUM, THEATRE_ID) VALUES (5, 0, '2021-05-11', 'B2', 1);
INSERT INTO THEATRE_SCREEN_1(THTR_BKNG_SCRN_ID, BOOKING_VRSN, DATE_OF_BOOKING, SEAT_NUM, THEATRE_ID) VALUES (6, 0, '2021-05-11', 'B3', 1);
INSERT INTO THEATRE_SCREEN_1(THTR_BKNG_SCRN_ID, BOOKING_VRSN, DATE_OF_BOOKING, SEAT_NUM, THEATRE_ID) VALUES (7, 0, '2021-05-11', 'C1', 1);
INSERT INTO THEATRE_SCREEN_1(THTR_BKNG_SCRN_ID, BOOKING_VRSN, DATE_OF_BOOKING, SEAT_NUM, THEATRE_ID) VALUES (8, 0, '2021-05-11', 'C2', 1);
INSERT INTO THEATRE_SCREEN_1(THTR_BKNG_SCRN_ID, BOOKING_VRSN, DATE_OF_BOOKING, SEAT_NUM, THEATRE_ID) VALUES (9, 0, '2021-05-11', 'C3', 1);


INSERT INTO USER(USER_PHNE_NB, USER_ID, USER_MAIL_ID, USER_PASS_WD, USER_ROLE, USR_VERSION) VALUES ('9666682391', 'BMSANVESH', 'knagaanvesh@gmail.com', 'test@123', 'ADMIN', 0);
INSERT INTO USER(USER_PHNE_NB, USER_ID, USER_MAIL_ID, USER_PASS_WD, USER_ROLE, USR_VERSION) VALUES ('9666682390', 'BMSNAGA', 'knagaanvesh1@gmail.com', 'test@123', 'USER', 0);


INSERT INTO API_PERMS(URI, ACTION, ROLES) VALUES ('/bookTickets','PUT','USER, ADMIN');
INSERT INTO API_PERMS(URI, ACTION, ROLES) VALUES ('/moviesLst','GET','USER, ADMIN');
INSERT INTO API_PERMS(URI, ACTION, ROLES) VALUES ('/theatres','GET','USER, ADMIN');
INSERT INTO API_PERMS(URI, ACTION, ROLES) VALUES ('/generateToken','PUT','USER, ADMIN');
INSERT INTO API_PERMS(URI, ACTION, ROLES) VALUES ('/addUser','POST','ADMIN');
